name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, edited, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --network-concurrency 1 --frozen-lockfile

      - run: yarn lint
